# Generated by Django 4.2 on 2025-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materia",
            name="anio",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materia",
            name="contenidos_minimos",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
