# Generated by Django 4.2 on 2025-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_materia_anio_materia_contenidos_minimos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materia",
            name="contenidos_minimos",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
