# Generated by Django 4.2 on 2025-02-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_materia_contenidos_minimos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nota",
            name="anio",
        ),
        migrations.AddField(
            model_name="nota",
            name="cuatrimestre_1_informe_1",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
