# Generated by Django 4.2 on 2025-02-09 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_nota_cuatrimestre_1_informe_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boletin",
            name="periodos",
        ),
        migrations.AddField(
            model_name="boletin",
            name="anio",
            field=models.IntegerField(
                default=2025,
                validators=[django.core.validators.MinValueValidator(2025)],
            ),
        ),
    ]
