# Generated by Django 4.2 on 2025-02-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_boletin_periodos_boletin_anio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boletin",
            name="colegio",
        ),
    ]
