# Generated by Django 4.2 on 2025-02-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_boletin_colegio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boletin",
            name="inasistencia",
        ),
        migrations.AddField(
            model_name="boletin",
            name="asistencia",
            field=models.IntegerField(default=0),
        ),
    ]
