# Generated by Django 4.2 on 2025-02-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_boletin_inasistencia_boletin_asistencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletin",
            name="faltas_injustificadas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boletin",
            name="faltas_justificadas",
            field=models.IntegerField(default=0),
        ),
    ]
