# Generated by Django 4.2 on 2025-02-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_boletin_faltas_injustificadas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="notas",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
