# Generated by Django 4.2 on 2025-02-11 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_nota_notas"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletin",
            name="anio_calendario",
            field=models.IntegerField(
                default=2025,
                validators=[django.core.validators.MinValueValidator(2025)],
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="anio",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="boletin",
            name="anio",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
    ]
