# Generated by Django 4.2 on 2025-02-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_boletin_anio_calendario_nota_anio_alter_boletin_anio"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoletinImpresion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alumno", models.CharField(max_length=100)),
                ("curso", models.CharField(max_length=50)),
                ("año", models.IntegerField()),
                ("materia_1", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_2", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_3", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_4", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_5", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_6", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_7", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_8", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_9", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_10", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_11", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_12", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_13", models.CharField(blank=True, max_length=5, null=True)),
                ("materia_14", models.CharField(blank=True, max_length=5, null=True)),
                ("inasistencias_injustificadas", models.IntegerField(default=0)),
                ("inasistencias_justificadas", models.IntegerField(default=0)),
            ],
        ),
    ]
