# Generated by Django 4.2 on 2025-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_boletinimpresion"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
