# Generated by Django 4.2 on 2025-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_usuario_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
