# Generated by Django 4.2 on 2025-02-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_usuario_url"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
    ]
