# Generated by Django 4.2 on 2025-02-22 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_usuario_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletin",
            name="preceptor_titular",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "preceptor"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boletin_preceptor_titular",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="profesor_titular",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "profesor"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_profesor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="boletin",
            name="alumno",
            field=models.OneToOneField(
                limit_choices_to={"rol": "alumno"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boletin_alumno",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="alumno",
            field=models.ForeignKey(
                limit_choices_to={"rol": "alumno"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_alumno",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
