# Generated by Django 4.2 on 2025-02-22 20:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_boletin_preceptor_titular_nota_profesor_titular_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boletin',
            new_name='Cursada',
        ),
    ]
