# Generated by Django 4.2 on 2025-02-22 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_cursada_delete_boletin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursada",
            name="alumno",
            field=models.OneToOneField(
                limit_choices_to={"rol": "alumno"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursada_alumno",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cursada",
            name="preceptor_titular",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "preceptor"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursada_preceptor_titular",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
