# Generated by Django 4.2 on 2025-02-24 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_cursada_alumno_alter_cursada_preceptor_titular"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="cuatrimestre_final",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
