# Generated by Django 4.2 on 2025-02-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_nota_cuatrimestre_final"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nota",
            old_name="cuatrimestre_final",
            new_name="nota_final",
        ),
    ]
