import environ
import os
from datetime import timedelta
from django.core.cache import cache

"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1mp@@+^f@@x*8@0r=r4r$gqk!d&$=*bw58jf$6t&1bv%ay9t6f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


JAZZMIN_SETTINGS = {
    "site_logo": "img/logo.png", 
    "site_title": "Mi Proyecto",
    "site_header": "Panel de Administración",
    "welcome_sign": "Bienvenido a Colegio Dr. Guevara",
    "copyright": "Trabajo realizado por Arella Catucci",
    "search_model": ["auth.User", "core.Cursada"],
}


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Django REST Framework y JWT
    'rest_framework',
    'rest_framework_simplejwt',
    # Swagger
    'drf_yasg', 

    "core"
]

# Configuración de Django REST Framework y JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Solo permite acceso a usuarios autenticados por defecto
    ),
}

# Configuración de JWT Token
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Token válido por 1 día
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # Token de refresco válido 7 días
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Inicializar django-environ
env = environ.Env()
#environ.Env.read_env()  # Lee el archivo .env

#env_file = '.env.development' if DJANGO_ENV == 'development' else '.env.production'
env_file = '.env'
environ.Env.read_env(env_file)


# Configuración de la base de datos usando las variables de entorno
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  
        'HOST': env('DB_HOST', default='localhost'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'PORT': env('DB_PORT')
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'  # Idioma español
TIME_ZONE = 'America/Argentina/Buenos_Aires'  # Ajusta la zona horaria si es necesario
USE_I18N = True
USE_L10N = True
USE_TZ = True



# Configuración de archivos estáticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Carpeta donde puedes poner archivos estáticos personalizados
]
print(STATICFILES_DIRS)
STATIC_ROOT = BASE_DIR / "staticfiles"  # Para recoger los archivos estáticos en producción

# Archivos de medios (si usas imágenes o archivos subidos por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = 'core.Usuario'

CSRF_TRUSTED_ORIGINS = [
    'https://mi-dominio.com',
    'https://*.ngrok-free.app',  # 🔹 Permite cualquier subdominio de ngrok
]


CACHES = {
    'default': {
        #'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
